name: Code push
run-name: changes made by ${{ github.actor }}
on:
  pull_request:
    branches: [main, develop]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.x', '18.x']
    steps:
      - run: echo "Event - ${{ github.event_name }}"
      - run: echo "Server - ${{ runner.os }}"
      - run: echo "Branch - ${{ github.ref }}"
      - run: echo "Repository - ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - run: echo "🍏 This job's status is ${{ job.status }}."
